stock_prices:
  outputs:
    dev:
      account: "HQB67722"
      user: "PranavReddy02"
      password: "Vanarp@02082001"
      role: "ACCOUNTADMIN"
      database: "stock_db"
      warehouse: "stock_warehouse"
      schema: "analytics"
      type: "snowflake"
      threads: 1
  target: dev


